### PR TITLE
Also cleanup `MqttClientSessionsManager._subscriberSessions` when session is taken over by a new one with CleanSession=true, fix #1552

### LINKED ISSUE #1552: MQTTnet.Server.MqttClientSessionsManager._subscriberSessions is not proper removed on special case.
### Describe the bug
`MQTTnet.Server.MqttClientSessionsManager._subscriberSessions` is not proper removed on special case.

Run the below code(more than one client connect with the same id, so they will keep disconnect and connect again)
And wait some seconds, you can see more and more entity(memory leak) in `MQTTnet.Server.MqttClientSessionsManager._subscriberSessions`, and publish a single message will be queue more and more times.

Seems the below code will create a new session, but never remove the old one from _subscriberSessions
https://github.com/dotnet/MQTTnet/blob/d2ce9d607a0058d53bc46bb594b6af44e9a1925c/Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs#L496-L500

### Which component is your bug related to?
- Server 

### To Reproduce
1. Using this version of MQTTnet `4.1.2.350`.
2. Run the below code.
3. Wait some seconds and see memory leak.

### Expected behavior
No memory leak will happen, `MqttClientSessionsManager._subscriberSessions` should not have more than one member, like it does in `MqttClientSessionsManager._clients`

### Code example
Please provide full code examples below where possible to make it easier for the developers to check your issues.

**Ideally a Unit Test (which shows the error) is provided so that the behavior can be reproduced easily.**

<details>
<summary>Old src(with ManagedMqttClient)</summary>

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="4.1.2.350" />
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.1.2.350" />
  </ItemGroup>

</Project>
```
```cs
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Diagnostics;
using MQTTnet.Extensions.ManagedClient;
using MQTTnet.Server;
using System.Text;

namespace mqtt_test
{
    internal class Program
    {
        static IMqttNetLogger logger = new MqttNet2NLogLogger();

        static async Task Main(string[] args)
        {
            var factoryWithLogger = new MqttFactory(logger);
            var srv = factoryWithLogger.CreateMqttServer(new MqttServerOptionsBuilder()
                .WithDefaultEndpoint()
                .Build());
            await srv.StartAsync();

            var factoryNoLogger = new MqttFactory(MqttNetNullLogger.Instance);
            IManagedMqttClient[] clis = new IManagedMqttClient[10];
            for (int i = 0; i < clis.Length; ++i)
            {
                var cli = factoryNoLogger.CreateManagedMqttClient(factoryNoLogger.CreateMqttClient());
                await cli.StartAsync(new ManagedMqttClientOptions
                {
                    AutoReconnectDelay = TimeSpan.FromMilliseconds(100),
                    ClientOptions = new MqttClientOptions
                    {
                        ClientId = "disconnect_with_same_cli_id",
                        ChannelOptions = new MqttClientTcpOptions
                        {
                            Server = "127.0.0.1",
                            Port = 1883
                        }
                    }
                });
                await cli.SubscribeAsync("#");
                clis[i] = cli;
            }

            while (true)
            {
                await Task.Delay(1000);
                await srv.InjectApplicationMessage(new InjectedMqttApplicationMessage(new MqttApplicationMessage
                {
                    Topic = "tick",
                    Payload = Encoding.UTF8.GetBytes(DateTime.Now.ToString())
                }
                )
                {
                    SenderClientId = "server"
                });
            }
        }

        private sealed class MqttNet2NLogLogger : IMqttNetLogger
        {
            public bool IsEnabled => true;

            public void Publish(MqttNetLogLevel logLevel, string source, string message, object[] parameters, Exception exception)
            {
                if (parameters?.Length > 0 && !string.IsNullOrEmpty(message))
                {
                    try
                    {
                        message = string.Format(message, parameters);
                    }
                    catch
                    {
                        message = "***FAILED TO FORMAT***: " + message;
                    }
                }
                lock (this)
                {
                    Console.WriteLine(message);
                }
            }
        }
    }
}
```

</details>

<details>
<summary>Updated src(without ManagedMqttClient)</summary>

```cs
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Diagnostics;
using MQTTnet.Server;
using System.Text;

namespace mqtt_test
{
    internal class Program
    {
        static IMqttNetLogger logger = new MqttNet2NLogLogger();

        static async Task Main(string[] args)
        {
            var factoryWithLogger = new MqttFactory(logger);
            var srv = factoryWithLogger.CreateMqttServer(new MqttServerOptionsBuilder()
                .WithDefaultEndpoint()
                .Build());
            await srv.StartAsync();

            var factoryNoLogger = new MqttFactory(MqttNetNullLogger.Instance);
            for (int i = 0; ; ++i)
            {
                var cli = factoryNoLogger.CreateMqttClient();
                var tcs = new TaskCompletionSource<bool>();
                cli.ApplicationMessageReceivedAsync += m =>
                {
                    //lock (logger)
                    //{
                    //    Console.WriteLine(Encoding.UTF8.GetString(m.ApplicationMessage.Payload));
                    //}
                    tcs.SetResult(true);
                    return Task.CompletedTask;
                };
                await cli.ConnectAsync(new MqttClientOptions
                {
                    ClientId = "disconnect_with_same_cli_id",
                    CleanSession = true,
                    ChannelOptions = new MqttClientTcpOptions
                    {
                        Server = "127.0.0.1",
                        Port = 1883
                    }
                });
                await cli.SubscribeAsync("#");
                await srv.InjectApplicationMessage(new InjectedMqttApplicationMessage(new MqttApplicationMessage
                {
                    Topic = "tick",
                    Payload = Encoding.UTF8.GetBytes(DateTime.Now.ToString())
                }
                )
                {
                    SenderClientId = "server"
                });
                await tcs.Task;
                //if (i % 1024 == 0)
                //    GC.Collect();
                //await Task.Delay(100);
                //await cli.DisconnectAsync();
            }
        }

        private sealed class MqttNet2NLogLogger : IMqttNetLogger
        {
            public bool IsEnabled => true;

            public void Publish(MqttNetLogLevel logLevel, string source, string message, object[] parameters, Exception exception)
            {
                if (parameters?.Length > 0 && !string.IsNullOrEmpty(message))
                {
                    try
                    {
                        message = string.Format(message, parameters);
                    }
                    catch
                    {
                        message = "***FAILED TO FORMAT***: " + message;
                    }
                }
                lock (this)
                {
                    Console.WriteLine(message);
                }
            }
        }
    }
}
```

</details>

### PR DESCRIPTION
**Pull request by yyjdelete**
Fix #1552

### CODE REVIEW

File: Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs [hunk 1]
```diff
@@ -544,6 +548,8 @@ MqttClient CreateClient(MqttConnectPacket connectPacket, IMqttChannelAdapter cha
                         await _eventContainer.ClientDisconnectedEvent.InvokeAsync(eventArgs).ConfigureAwait(false);
                     }
                 }
+
+                oldSession?.Dispose();
```
Comment (yyjdelete) [inline Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs:552]: During test, I found  if `SemaphoreSlim.Dispose()` is called here, `SemaphoreSlim.WaitAsync(ct)` failed to be cancelled and will never return

Comment (chkr1011) [reply Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs:552]: Please do not change the dispose call yet. I am aware of this issue and already creating a new primitive as a replacement for the semaphore. After you reverted the Dispose call changes, we can merge this pull request because the other changes are very good and not dangerous.

Comment (yyjdelete) [reply Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs:552]: @chkr1011 Updated. 
Should `oldSession?.Dispose()` be kept as it is?
Seems the leak caused by `SemaphoreSlim.Dispose()` will only happen when debug in VS with `Task.s_currentActiveTasks` and will not happen in normal run.

Comment (chkr1011) [reply Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs:552]: Please keep ist.
