### PR TITLE
#1612 fix wildcard topic subscription

### LINKED ISSUE #1612: [MqttServer] Subscription to similar base and subtopic with wildcards fails
We encountered a bug which was not present in earlier major versions of MQTTnet, but we met it since we had a major upgrade to 4.1.2.350. Same applies for the newest version 4.1.2.436

We start an MQTTnet server. Then a client. We add a subscription to these to topics:

house/+/room
house/+/room/+

Then we send messages with these two topics:

house/1/room
house/1/room/bed

**We would expect to receive both messages, but only the first one arrives**. When testing this with other servers (older MQTTnet server or Moquitto) both messages arrive. 

As you can see in the sample code below, we also made some slight variations (# instead of +), but no success. When we only use one subscription (#) everything is fine again. Replacing the mid-level wildcard with a concrete house id (1) also makes it work again.

It is not an ultra-critical bug, since there is a workaround. But we lost data in production since we did not realize this problem immediately. Might be that some others may stumble over this, too.
 
```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Server;

namespace MqttServerTest
{
	class Program
	{
		static void Main(string[] args)
		{
			Task.Run(StartMqttServer).Wait();

			var client = Task.Run(StartClient).Result;

			client.SubscribeAsync("house/+/room");
			client.SubscribeAsync("house/+/room/+");

			//You can try these two subscriptions instead, but this will also fail
			//client.SubscribeAsync("house/+/room");
			//client.SubscribeAsync("house/+/room/#");

			//This works
			//client.SubscribeAsync("house/1/room");
			//client.SubscribeAsync("house/1/room/+");

			//This works, too
			//client.SubscribeAsync("house/1/room/#");

			Publish(client, "house/1/room");
			Publish(client, "house/1/room/bed");

			//Result with first two examples: Only first message will be shown

			Console.ReadLine();
		}

		static async Task<MqttServer> StartMqttServer()
		{
			var mqttFactory = new MqttFactory();
			
			var mqttServerOptions = 
				mqttFactory
					.CreateServerOptionsBuilder()
					.WithDefaultEndpoint()
					.Build();
			var server = mqttFactory.CreateMqttServer(mqttServerOptions);
			await server.StartAsync();
			return server;
		}
		
		static async Task<IMqttClient> StartClient()
		{
			var mqttFactory = new MqttFactory();

			var mqttClientOptions =
				mqttFactory
					.CreateClientOptionsBuilder()
					.WithTcpServer("localhost")
					.WithClientId("test")
					.Build();

			var client = mqttFactory.CreateMqttClient();

			client.ApplicationMessageReceivedAsync += args =>
			{
				Console.WriteLine(args.ApplicationMessage.Topic);
				return Task.CompletedTask;
			};

			await client.ConnectAsync(mqttClientOptions, CancellationToken.None);
			
			return client;
		}
		
		private static Task<MqttClientPublishResult> Publish(IMqttClient client, string topic)
		{
			return client.PublishAsync(new MqttApplicationMessage
			{
				Topic = topic,
				Payload = new byte[] { 1, 2, 3, 4 }
			});
		}
	}
}
```

### PR DESCRIPTION
**Pull request by logicaloud**
Fixes #1612 

There was an error in the early elimination of wildcard topics. It worked under the assumption that the same topic hash will have the same topic hash mask, which is not always the case for wildcard topics. This is fixed by storing wildcard subscriptions by topic hash mask and by comparing against the correct hash mask at the elimination stage. Unit test added also.

### CODE REVIEW

**Comment by xljiulang** [comment]
👍

File: Source/MQTTnet/Server/Internal/MqttClientSubscriptionsManager.cs [hunk 1]
```diff
@@ -60,13 +60,16 @@ public CheckSubscriptionsResult CheckSubscriptions(string topic, ulong topicHash
...
-                    if ((topicHash & subscriptionHashMask) == subscriptionHash)
+                    var subscriptionsByHashMask = wcs.Value.SubscriptionsByHashMask;
+                    foreach (var shm in subscriptionsByHashMask)
                     {
-                        possibleSubscriptions.AddRange(wildcardSubscriptions.Subscriptions.ToList());
+                        var subscriptionHashMask = shm.Key;
+                        if ((topicHash & subscriptionHashMask) == subscriptionHash)
+                        {
+                            var subscriptions = shm.Value;
+                            possibleSubscriptions.AddRange(subscriptions.ToList());
```
Comment (chkr1011) [inline Source/MQTTnet/Server/Internal/MqttClientSubscriptionsManager.cs:71]: Is the call of "ToList()" really required? If not, it is only a useless allocation.

Comment (logicaloud) [reply Source/MQTTnet/Server/Internal/MqttClientSubscriptionsManager.cs]: Good point, that's redundant. I did not notice a change in performance with a cursory look; maybe it's optimized away. I'll do some benchmarking to compare against https://github.com/dotnet/MQTTnet/pull/1298#issuecomment-1036967766 to see if anything else has changed, also in respect of the new AsyncLock.
